### ISSUE TITLE
how to use in yii2-advanced

### ISSUE THREAD

**Issue by hustcrab** [yii2mod/yii2-comments#10]
I don't know `<?php echo \yii2mod\comments\widgets\Comment::widget([
    'model' => $model,
    'relatedTo' => 'User ' . \Yii::$app->user->identity->username . ' commented on the page ' . \yii\helpers\Url::current() // for example
]); ?>` about what is the '$model'. Is't a model =new user?

**Comment by ihorchepurnyi** [comment]
Hi,  for example:

``` php
$model = PostModel::findOne(['title' => 'some post title']);
$model = UserModel::find()->where(['email' => 'some email'])->one();
```

**Comment by hustcrab** [comment]
Can I use it in yii2 -advanced/frontend/views straightly? Thank you.

**Comment by hustcrab** [comment]
I saw the second closed issues. May I have to use 'en-US' in my application if I want to use this.

**Comment by ihorchepurnyi** [comment]
> Can I use it in yii2 -advanced/frontend/views straightly? Thank you.

yes, of course. Code for example:

``` php

// In your controller

$post = PostModel::findOne(['title' => 'your post title']);

return $this->render('your view', [
  'post' => $post
]);

// In your view file

<?php echo \yii2mod\comments\widgets\Comment::widget([
    'model' => $post,
    'relatedTo' => 'User ' . \Yii::$app->user->identity->username . ' commented on the page ' . \yii\helpers\Url::current() // for example
]); ?>


```

> May I have to use 'en-US' in my application if I want to use this.

Yes, of course.  Yii2 by default used the 'en-US' language.

**Comment by hustcrab** [comment]
What's the 'PostModel' ?

**Comment by ihorchepurnyi** [comment]
> What's the 'PostModel' ?

This model just for example, you need to use your own models in your project.
