### ISSUE TITLE
Переход с 1.0.3 на 1.0.4

### ISSUE THREAD

**Issue by vityapro** [yii2mod/yii2-comments#13]
Здраствуйте после обновления компосером модуля с 1.0.3 на 1.0.4 возникла ошибка из за новго поля в таблице relatedTo (вероятно из за того что в миграции не предусмотрена проверка на существование таблици) + название миграции не позволяет ее накактить снова.
Как решение проблемы хотел бы предложить вместо одной миграции сделдать последовательность миграций.

(Нехотелось создавать еще одно issuse)
Есть следующая проблема, на сайте используеться два модуля комментариев поэтому название   модуля (comment) уже занято, есть ли корректный способ передать в модели модуля другое название без переопределения их в каталогах проекта ?
П.С. Спасибо за отличный модуль

**Comment by ihorchepurnyi** [comment]
Здравствуйте

> Как решение проблемы хотел бы предложить вместо одной миграции сделдать последовательность миграций.

Добавил миграцию

> есть ли корректный способ передать в модели модуля другое название без переопределения их в каталогах проекта

Сейчас кроме переопределения модели способа нет. Сегодня гляну что можно сделать.

Большое спасибо за ваш отзыв.

**Comment by ihorchepurnyi** [comment]
Глянул, на скорую руку точно не получится сделать, так как от модуля виджет и контроллер зависит. Я так понимаю, вам нужно переопределить метод `getAuthor()` ?

**Comment by vityapro** [comment]
переопределить название модуля а иммено в Module.php переменную $name которая инициируеться в модели а потом юзаеться практически в большинстве моделей и выходит что нужно переопределить их все

**Comment by ihorchepurnyi** [comment]
да, честно говоря пока не смогу вам подсказать другого способа.

**Comment by vityapro** [comment]
Хорошо спасибо и на этом)
