### ISSUE TITLE
how to entry entity , entityId, and relatedTo

### ISSUE THREAD

**Issue by dzas42** [yii2mod/yii2-comments#15]
when i used this widget ,, the first show error 'The "entityIdAttribute" value for widget model cannot be empty,,, and widgets there are column entity , entitiyId and relatedTo,, how to use entry this column

**Comment by ihorchepurnyi** [comment]
Hi, please describe in more details the issue

**Comment by ihorchepurnyi** [comment]
Your model must have a primary key column, by default widget used the `id` attribute from your model. If the primary key in your model has another name, then you can change the name of `entityIdAttribute` by the following code:

``` php
<?php echo \yii2mod\comments\widgets\Comment::widget([
    'model' => $model,
    'entityIdAttribute' => 'name of primary key attribute from your model'
]); ?>
```

**Comment by dzas42** [comment]
that is work but button delete and replay is not work and pjax is not working 
![Uploading `error.png…]()`
in firebug error
TypeError: jQuery(...).comment is not a function
jQuery('#comment-form').comment({"pjaxContainerId":"#","formSelector":"#comment-...

**Comment by ihorchepurnyi** [comment]
How i can reproduce it? Can you add your code with model and widget setup here?

**Comment by ihorchepurnyi** [comment]
Now i try the following code and the `reply` and  `delete` functionality works perfectly.

``` php
$model = CmsModel::findOne(1);

<?php echo Comment::widget([
            'model' => $model,
            'entityIdAttribute' => 'idkey'
        ]); ?>
```

**Comment by dzas42** [comment]
// in view
<?php 

echo \yii2mod\comments\widgets\Comment::widget([
        'model' => $model,
        'entityIdAttribute' => 'id'
        //'entity'=>'test',
        // 'entityId'=>1,
]);

// in model
        $model =  \yii2mod\comments\models\CommentModel::findOne(1);
but this is same error,,,

**Comment by ihorchepurnyi** [comment]
$model is an entity to which a comment is added. For example Post, Cms, etc..

**Comment by ihorchepurnyi** [comment]
For example, if you want to add the comments to the some post you can try the following code:

``` php
$model = Post::find()->where(['title' => 'some post title'])->one();
 // and just put your model to the widget.
<?php echo \yii2mod\comments\widgets\Comment::widget([
        'model' => $model,
 ]);
```
