### ISSUE TITLE
Change / request

### ISSUE THREAD

**Issue by fourclub** [yii2mod/yii2-comments#19]
Если соединение интернет не очень хорошее, то, можно нажать много раз на кнопку отправить комментарий и он много раз подряд его отправит.

Нужно блокировать кнопку после первого нажатия до полной отправки комментария.

Google Translate
If Internet connection is not very good , then you can click the button several times to make a comment and he many times in a row it sends .

It is necessary to block the button after the first click to the full post a comment

**Comment by jsobers1331** [comment]
the module does this already. Issue you are having is that your browser isn't getting back the success acknowledgement fast enough. So to the end user it appears it's taking too long to add comment but the database is already updated with each timestamp entry.
