### ISSUE TITLE
questions  / request

### ISSUE THREAD

**Issue by fourclub** [yii2mod/yii2-comments#20]
1. Сделать полный перевод расширения, включая кнопки "Удалить" и "Ответить" (которые в данный момент нельзя перевести i18n)
2. Как правильно подключать свой вид на yii2-advanced
   пробовал:
   ставлю - 'commentView' => '@frontend/views/comments/index'
   получаю - Invalid Parameter – yii\base\InvalidParamException

-- Google Translate --- 
1. Make a full translation of the expansion, including the "Delete" button, and "Reply" (which at the moment can not translate i18n)
1. How to connect your view of the yii2-advanced
   I tried:
   use - 'commentView' => '@frontend/views/comments/index'
   I get - Invalid Parameter – yii\base\InvalidParamException

**Comment by ihorchepurnyi** [comment]
> Как правильно подключать свой вид на yii2-advanced
> пробовал:
> ставлю - 'commentView' => '@frontend/views/comments/index'
> получаю - Invalid Parameter – yii\base\InvalidParamException

Can you paste the full message of your error?

**Comment by ihorchepurnyi** [comment]
> Сделать полный перевод расширения, включая кнопки "Удалить" и "Ответить" (которые в данный момент нельзя перевести i18n)

Resolved by commit [d698654](https://github.com/yii2mod/yii2-comments/commit/d698654fd8d21839ea26008c07523756fe8361de)

**Comment by fourclub** [comment]
Спасибо за перевод нужный., обновился.

По ошибке, так пойдет? 
Invalid Parameter – yii\base\InvalidParamException
The view file does not exist: W:\domains***********\frontend\views\comments\index.php

**Comment by ihorchepurnyi** [comment]
> Invalid Parameter – yii\base\InvalidParamException
> The view file does not exist: W:\domains***********\frontend\views\comments\index.php

Hi, i tested this extension on the yii2-avanced tempalate without any errors. Are you sure that you create the view file(@frontend/views/comments/index)? This error tells that the view file does not exists in your folder.

**Comment by fourclub** [comment]
I'm sorry , did not notice the missing letter in the name, it's my fault . Fixed, I checked again and everything works. 

Close this issue
