### ISSUE TITLE
Embedding

### ISSUE THREAD

**Issue by robov** [yii2mod/yii2-comments#22]
Your extensions looks amazing by the way. !!!!
I noticed that I can type in html and iframes etc... This can pose a security risk...
This way people can add malicious scrips to my app

**Comment by ihorchepurnyi** [comment]
Hi, users can't add malicious scrips to your app because we used the [HTML Purifier](http://htmlpurifier.org/) for the comments content.
You can change the configuration for the `PurifyBehavior` by creating your own CommentModel.

**Comment by ihorchepurnyi** [comment]
HTML Purifier examples:
- [Malicious code removed](http://htmlpurifier.org/demo.php?html=%3Cimg+src%3D%22javascript%3Aevil%28%29%3B%22+onload%3D%22evil%28%29%3B%22+%2F%3E)
- [Missing end tags fixed](http://htmlpurifier.org/demo.php?html=%3Cb%3EBold&submit=Submit)
- [Illegal nesting fixed](http://htmlpurifier.org/demo.php?html=%3Cb%3EInline+%3Cdel%3Econtext+%3Cdiv%3ENo+block+allowed%3C%2Fdiv%3E%3C%2Fdel%3E%3C%2Fb%3E&submit=Submit)
- [Deprecated tags converted](http://htmlpurifier.org/demo.php?html=%3Ccenter%3ECentered%3C%2Fcenter%3E&filter%5BHTML.Doctype%5D=XHTML+1.0+Strict&submit=Submit)
- [CSS validated](http://htmlpurifier.org/demo.php?html=%3Cspan+style%3D%22color%3A%23COW%3Bfloat%3Aaround%3Btext-decoration%3Ablink%3B%22%3EText%3C%2Fspan%3E&submit=Submit)
- [Rich formatting preserved](http://htmlpurifier.org/demo.php?html=%3Ctable%3E%0D%0A++%3Ccaption%3E%0D%0A++++Cool+table%0D%0A++%3C%2Fcaption%3E%0D%0A++%3Ctfoot%3E%0D%0A++++%3Ctr%3E%0D%0A++++++%3Cth%3EI+can+do+so+much%21%3C%2Fth%3E%0D%0A++++%3C%2Ftr%3E%0D%0A++%3C%2Ftfoot%3E%0D%0A++%3Ctr%3E%0D%0A++++%3Ctd+style%3D%22font-size%3A16pt%3B%0D%0A++++++color%3A%23F00%3Bfont-family%3Asans-serif%3B%0D%0A++++++text-align%3Acenter%3B%22%3EWow%3C%2Ftd%3E%0D%0A++%3C%2Ftr%3E%0D%0A%3C%2Ftable%3E&experimental=1&submit=Submit)
