### ISSUE TITLE
malformed utf-8 characters possibly incorrectly encoded php

### ISSUE THREAD

**Issue by mkhalil49** [yii2mod/yii2-comments#23]
When add a comment 
gives me 
malformed utf-8 characters possibly incorrectly encoded

and i resolved it by 

```
  $decryptEntity = Yii::$app->getSecurity()->decryptByKey(utf8_decode($entity), $module::$name);
```

and

```
return utf8_encode(Yii::$app->getSecurity()->encryptByKey(Json::encode([
            'entity' => $this->entity,
            'entityId' => $this->entityId,
            'relatedTo' => $this->relatedTo
        ]), Module::$name));
```

thanks

**Comment by ihorchepurnyi** [comment]
Hi, how i can reproduce your issue?

**Comment by mkhalil49** [comment]
i am using Arabic language my encoding  utf-8 but when i add the comment gives me that error
when i searched i found a similar issue that helped me fix that
[http://stackoverflow.com/questions/29191580/how-can-i-save-an-encrypted-data-using-yiiapp-security-encryptbykey-in-yi](http://stackoverflow.com/questions/29191580/how-can-i-save-an-encrypted-data-using-yiiapp-security-encryptbykey-in-yi)

**Comment by ihorchepurnyi** [comment]
issue was fixed, please update the package via `composer update` command.
