### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by robov** [yii2mod/yii2-comments#25]
Can I make a request for a feature?
Add some custom data to the widget setting
and be able to show only those with that setting

ie

```
    'model' => $model,
'language' => 'de',
'languageStrict' => TRUE,
    'relatedTo' => 'User...
```

This stores de in the record field 'language'
if languageStrict== TRUE then it only shows those records where the languageis the same (de)
if languageStrict== FALSE it shows ALL the records (like current)

This way people can easy implement  multilingual

I could ofcourse copy your code and modify it...but this way more people can benefit from your work

**Comment by ihorchepurnyi** [comment]
Hi, i'm not sure that this functionality is needed for the basic comments widget. You can override the comment model and implement this feature for your own project.

@disem what do you think about this feature?
