### ISSUE TITLE
Do comment moderation is?

### ISSUE THREAD

**Issue by i-coder** [yii2mod/yii2-comments#26]
Do comment moderation is? To comment moderation were initially

**Comment by disem** [comment]
**Comments management section setup**

To access the comments management section, you need to add the following code to your application configuration:

``` php
  'controllerMap' => [
      'comments' => 'yii2mod\comments\controllers\ManageController'
  ]  
```

> Basically the above code must be placed in the `admin` module

You can then access to management section through the following URL:
http://localhost/path/to/index.php?r=comments/index

> If you have added this controller in the module admin, the URL will look like the following
> http://localhost/path/to/index.php?r=admin/comments/index
