### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by quinlena** [yii2mod/yii2-comments#27]
Добрый день! А есть ли возможность вывода постранично разбив комментарии?

**Comment by ihorchepurnyi** [comment]
Добрый день, пока нет такой возможности.

**Comment by quinlena** [comment]
Может кому понадобится, оставлю тут:
`<?php
$provider = new ArrayDataProvider([
    'allModels' => $comments,
    'pagination' => [
        'pageSize' => 1,
    ],
    'sort' => [
        'attributes' => ['createdAt'],
    ],
]);
?>`
Это в файле _list.php

Потом ниже

`<?php foreach ($provider->getModels() as $comment) : ?>`

И внизу выводим пагинацию.
