### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by seesoft-dev** [yii2mod/yii2-comments#36]
why there is no navigation through pages, it is not convenient when all comm displayed? (sorry for my English)

**Comment by ihorchepurnyi** [comment]
Hi, We have started the new comments module 2.0 with the following features:
 - pagination
 - moderation
 - and other small changes

**Comment by seesoft-dev** [comment]
do you have a beta version ?)

**Comment by Gawran** [comment]
Please, consider possibility of translating module without global language
settings and possibility for comment author to change/delete the comment.
It is fine to give that rights to administration role but it really should
be on author level too. Soft delete is OK. I will contribute if I develop
those features myself.

23.11.2016. 13.05, "Igor Chepurnoy" notifications@github.com је
написао/ла:

**Comment by ihorchepurnyi** [comment]
@eolitich 
> do you have a beta version?

No, we don't have enough time.

**Comment by ihorchepurnyi** [comment]
@Gawran  Thanks for your feedback.

**Comment by ihorchepurnyi** [comment]
Resolved in release https://github.com/yii2mod/yii2-comments/releases/tag/1.9
