### ISSUE TITLE
Про comment.js и комментирование гостями

### ISSUE THREAD

**Issue by shah-typhoon** [yii2mod/yii2-comments#37]
Доброго времени суток!
Спасибо за Ваш модуль, среди всех я остановился именно на Вашем продукте. Но есть небольшие предложения и вопросы, которые хотелось бы прояснить.
1. Предложение: В функции reply и cancelReply в файле comment.js добавить триггер событий, что-то типа 'beforeMoveTextarea' и 'afterMoveTextarea', по которым можно обезопасить перемещение по странице, как-минимум, tinyMCE: поскольку в текущей версии редактор tinyMCE "зависает". В эти события можно было бы повесить собственные функции отключения редактора в момент переноса.
2. И совершенно необязательный, но желательный вопрос: что Вы думаете о комментировании сущностей гостями сайта? И стоит ли ожидать модернизацию системы комментирования в данном вопросе?
С уважением!

**Comment by ihorchepurnyi** [comment]
Здравствуйте, спасибо большое за ваш отзыв.

> Предложение: В функции reply и cancelReply в файле comment.js добавить триггер событий

События добавим.

> И совершенно необязательный, но желательный вопрос: что Вы думаете о комментировании сущностей гостями сайта? 

Об этом думали, но для этого нужно будет переделать структуру таблицы, модель, и возможно другие части системы. Возможно сделаем это в версии 2.0


В целом планируется переделка всего модуля, добавление пагинации, модерации, скорее всего изменение хранения дерева комментариев в пользу nestedSet. Пока над этими вопросами продолжаем думать.

**Comment by shah-typhoon** [comment]
Спасибо большое! Очень жду версию 2.0)

**Comment by ihorchepurnyi** [comment]
Здравствуйте, был выпущен новые релиз комментариев 1.9, в этом релизе добавлена поддержка пагинации, а также были добавлены другие улучшения. Посмотрите обновленный README и обновите свой пакет с помощью команды `composer update yii2mod/yii2-comments`
