### ISSUE TITLE
Нуждаюсь в помощи с конфигурацией

### ISSUE THREAD

**Issue by ghost** [yii2mod/yii2-comments#39]
Добрый день! Вопросы могут показаться глупыми, я неопытен и возможно просто упустил какую-то очевидную вещь. 
Установил данный модуль через composer на проект, основанный на yii2 advanced
в /common/config/main.php добавил это
![image](https://cloud.githubusercontent.com/assets/22449672/21099223/ab88e298-c075-11e6-8016-111186df5117.png)

и в /backend/config/main добавил следующее:
![image](https://cloud.githubusercontent.com/assets/22449672/21099234/c3544390-c075-11e6-8f0e-10001d73dd60.png)

почему-то при попытке зайти на site/admin/comments, я получаю ошибку 404. Перепробовал уже все варианты, не получается.

Можете помочь? 
Спасибо.

**Comment by morontt** [comment]
Пробовали перезагружать компьютер?

**Comment by ghost** [comment]
@morontt я ведь написал, что установкой модуля и его конфигурированием занимаюсь впервые. И вполне осознаю, что вопрос "школьного" уровня.

**Comment by morontt** [comment]
@ArthurKr Извиняюсь, это такой юмор :) Я не специалист по этому модулю, но он скоро тут появится.

**Comment by ihorchepurnyi** [comment]
Здравствуйте, вам в бекенде нужно добавить след. конфиг выше ключа `modules`
```php
  'controllerMap' => [
      'comments' => 'yii2mod\comments\controllers\ManageController',
 ]
```

То есть ваш конфиг должен быть
```php
'id' => 'app-backend'
'controllerMap' => [
      'comments' => 'yii2mod\comments\controllers\ManageController',
 ],
// 
```

**Comment by ihorchepurnyi** [comment]
и урл будет `http://backend.dev/comments/index`

**Comment by ghost** [comment]
@igor-chepurnoi заработало, спасибо! аж стыдно, вопрос реально глупый. Теперь ругается на интернационализацию, но с этим, думаю, управлюсь. Спасибо еще раз, можно закрывать.

**Comment by ihorchepurnyi** [comment]
Не за что :) Чтобы не ругалось на интернационализацию нужно добавить в конфиг след. код
```php
  'components' => [
        'i18n' => [
            'translations' => [
                'yii2mod.comments' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@yii2mod/comments/messages',
                ],
                // ...
            ],
        ],
        // ...
    ],
```

**Comment by ihorchepurnyi** [comment]
или чтобы не искало переводы в yii2mod, сделайте так.
```php
'i18n' => [
            'translations' => [
                '*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                ],
            ],
        ],
```

А потом когда переводы будут нужны, добавите код, который выше я написал.
