### ISSUE TITLE
Multiple widget on same page

### ISSUE THREAD

**Issue by bepehr** [yii2mod/yii2-comments#4]
Hi  , i want to use multiple comment widget on a page  , all things works fine but comment form dont work  , how i can do this ?

**Comment by ihorchepurnyi** [comment]
Hello, i'm sorry but the current implementation of the extension does not allow to use it twice on the page.

**Comment by bepehr** [comment]
Hi , do you have any plan to implement this ?

**Comment by ihorchepurnyi** [comment]
Hi, on this week i've planned to make it.

**Comment by bepehr** [comment]
Hi , i can help you if u need

**Comment by ihorchepurnyi** [comment]
I create new release, please update your package and check it.
Use following code for multiple widgets:

``` php
echo \yii2mod\comments\widgets\Comment::widget([
        'model' => $model,
    ]);

echo \yii2mod\comments\widgets\Comment::widget([
        'model' => $model2,
        'formId' => 'comment-form2'
    ]); 
```

**Comment by bepehr** [comment]
Hi , ty its works ! you saved my day ! :+1:

**Comment by ihorchepurnyi** [comment]
Your welcome.
