### ISSUE TITLE
My own model

### ISSUE THREAD

**Issue by ztdan4ik** [yii2mod/yii2-comments#43]
Доброе время суток. Столкнулся с ошибкой.

Что бы добавить возможность удаления своих комментариев я создал свою модель, в который дописал проверку в методе beforeModeration()

Подключаю модель:
```
'modules' => [
        'comment' => [
            'class' => 'yii2mod\comments\Module',
            'commentModelClass' => 'app\models\CommentModel',
        ]
    ]
```

В итоге комментарии подгружаются с использованием моей модели, но при удалении у меня беда:

> PHP Recoverable Error 'yii\base\ErrorException' with message 'Argument 1 passed to yii2mod\comments\events\CommentEvent::setCommentModel() **must be an instance of yii2mod\comments\models\CommentModel, instance of app\models\CommentModel given**, called in /home/admin/web/tasks.inde.pp.ua/public_html/vendor/yiisoft/yii2/base/Object.php on line 157 and defined' 
> 
> in /home/admin/web/tasks.inde.pp.ua/public_html/vendor/yii2mod/yii2-comments/events/CommentEvent.php:31

**Comment by ihorchepurnyi** [comment]
Здравствуйте, сегодня позже вечером проверю и отпишу.

**Comment by ihorchepurnyi** [comment]
А вы в своей модели наследовались от моей?

**Comment by ztdan4ik** [comment]
Упс... Нет, наследовался от ActiveRecord
Тыща извинений!

Спасибо!

**Comment by ihorchepurnyi** [comment]
Не за что)
