### ISSUE TITLE
Отображаются не все комментарии

### ISSUE THREAD

**Issue by A1exeyDunin** [yii2mod/yii2-comments#44]
Здравствуйте. Подскажите пожалуйста, в чем может быть такая проблема. Установил модуль по инструкции, комменты добавляются и выводятся. Но не все. То есть если я зайду на страницу, напишу пару комментов, все окей. Но если перезайду на другого юзера, то добавленные им комменты не выводятся или выводятся иногда. Как на скрине http://joxi.ru/82QM48Of0RYg2d , комментов 6, а выводится 2. И выводится они, как я понял, должны с последнего, но они так не делают. Использую такой вывод:
```
<?php echo \yii2mod\comments\widgets\Comment::widget([
                'model' => $comp,
                'relatedTo' => 'User ' . \Yii::$app->user->identity->username . ' commented on the page ' . \yii\helpers\Url::current(),
                'maxLevel' => 5,
                // set `pageSize` with custom sorting
                'dataProviderConfig' => [
                    'sort' => [
                        'attributes' => ['id'],
                        'defaultOrder' => ['id' => SORT_DESC],
                    ],
                    'pagination' => [
                        'pageSize' => 10
                    ],
                ],
                // your own config for comments ListView, for example:
                'listViewConfig' => [
                    'emptyText' => Yii::t('app', 'No comments found.'),
                ]
            ]); ?>
```

**Comment by ihorchepurnyi** [comment]
Здравствуйте, попробуйте убрать `maxLevel` и этот код
```php 
'pagination' => [
     'pageSize' => 10
],
```

**Comment by A1exeyDunin** [comment]
Я убрал что вы сказали, но изменений не последовало. Потом я подумал что может у комментов статус не соответствует, но все они были approver. Поставив одному коменту в ветке статус pending, все коменты отобразились. Так же и на другой странице, убрав комменты из веток, все отобразилось. Но стоит добавить коммент в ветку (reply) и обновить страницу, как добавленные комменты перестают показываться, хотя если продолжать ветку, то в ней все хорошо.

**Comment by ihorchepurnyi** [comment]
Сейчас проверю.

**Comment by ihorchepurnyi** [comment]
http://awesomescreenshot.com/06968bnre0

Вроде все работает, окружение следующее
- php 7.1
- apache
- mysql 5.7

Настройки виджета следующие:
```php
[
        'model' => $model,
        'relatedTo' => 'cms page: ' . $model->url,
],
```

**Comment by ihorchepurnyi** [comment]
Стоит отметить, если вы ставите комментарию статус например pending, то всем дочерним комментариям тоже самое ставиться статус pending и они не будут отображаться в ленте комментариев.

**Comment by A1exeyDunin** [comment]
Эх. Попробовал переустановить, не помогло. Сделал одноуровневые комменты. В моем случае их хватит.
