### ISSUE TITLE
Database Exception

### ISSUE THREAD

**Issue by carlosgarcia8** [yii2mod/yii2-comments#45]
I've been trying to work with this extension but when I try to see comments/index it says "SQLSTATE[42803]: Grouping error: 7 ERROR: column "a.username" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "c"."createdBy", "a"."username" FROM "comment" "c" LE..."
**getAuthors()**

I'm using Postgresql and I don't know if that's the problem. Thanks for the help.

**Comment by morontt** [comment]
@carlosgarcia8 Thanks for your feedback. Work in progress

**Comment by morontt** [comment]
@carlosgarcia8 Fixed
