### ISSUE TITLE
rying to get property of non-object

### ISSUE THREAD

**Issue by hecuervo** [yii2mod/yii2-comments#5]
![captura](https://cloud.githubusercontent.com/assets/2412743/13161643/ab47368c-d664-11e5-9966-fbfa52c817a2.PNG)

**Comment by ihorchepurnyi** [comment]
Add module to config section:

``` php
'modules' => [
    'comment' => [
        'class' => 'yii2mod\comments\Module'
    ]
]
```

**Comment by hecuervo** [comment]
hello again , show me this error.

Unable to locate message source for category 'yii2mod.enum'.

![captura](https://cloud.githubusercontent.com/assets/2412743/13583755/c7074fb6-e478-11e5-9280-9b5f3dcacb9e.PNG)

![captura](https://cloud.githubusercontent.com/assets/2412743/13583775/e4dd0314-e478-11e5-8873-8a5957193f44.PNG)

**Comment by ihorchepurnyi** [comment]
Hi, What language is used in your application? `en-US` ?

**Comment by varmad** [comment]
@hecuervo 

Have you solved this? am also getting the same issue.

**Comment by ihorchepurnyi** [comment]
Hi, you need to add the following code to your application configuration:

``` php
        'i18n' => [
            'translations' => [
                '*' => [
                    'class' => 'yii\i18n\PhpMessageSource'
                ],
            ],
        ],
```

**Comment by ihorchepurnyi** [comment]
I have fixed the following error for the yii2mod/enum

Please update your project by the following command

```
composer update
```

**Comment by varmad** [comment]
@igor-chepurnoi  thank you so much issue resolved
