### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by cobabikin** [yii2mod/yii2-comments#52]
![error](https://cloud.githubusercontent.com/assets/17420664/23213597/79692e1c-f946-11e6-8d1b-28df8725692d.PNG)

exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii2mod\comments\models\CommentModel::url' in C:\xampp\htdocs\yii2-core\vendor\yiisoft\yii2\base\Component.php:201
Stack trace:
#0 C:\xampp\htdocs\yii2-core\vendor\yiisoft\yii2\db\BaseActiveRecord.php(306): yii\base\Component->__set('url', '/article/fromte...')
#1 C:\xampp\htdocs\yii2-core\vendor\yiisoft\yii2\base\Model.php(698): yii\db\BaseActiveRecord->__set('url', '/article/fromte...')
#2 C:\xampp\htdocs\yii2-core\vendor\yiisoft\yii2\base\Model.php(827): yii\base\Model->setAttributes(Array)
#3 C:\xampp\htdocs\yii2-core\vendor\yii2mod\yii2-comments\controllers\DefaultController.php(86): yii\base\Model->load(Array)
#4 [internal function]: yii2mod\comments\controllers\DefaultController->actionCreate('\xC3\xA7\xC3\x91|\xC3\x82i(q0p\xC3\x9CF...')
#5 C:\xampp\htdocs\yii2-core\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\yii2-core\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\yii2-core\vendor\yiisoft\yii2\base\Module.php(522): yii\base\Controller->runAction('create', Array)
#8 C:\xampp\htdocs\yii2-core\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('comment/default...', Array)
#9 C:\xampp\htdocs\yii2-core\vendor\yiisoft\yii2\base\Application.php(379): yii\web\Application->handleRequest(Object(yii\web\Request))
#10 C:\xampp\htdocs\yii2-core\frontend\web\index.php(32): yii\base\Application->run()
#11 {main}

**Comment by ihorchepurnyi** [comment]
run the following command in your project
```bash
php yii migrate --migrationPath=@vendor/yii2mod/yii2-comments/migrations
```

**Comment by cobabikin** [comment]
ok man ...thanks FIX
