### ISSUE TITLE
How can i get the user id ?

### ISSUE THREAD

**Issue by eduardo-g-silva** [yii2mod/yii2-comments#54]
Hi thanks for the code I works fine and the readme helps a lot to implement it.

I am overriding the _list.php to add a link to the user profile. 
in the model i can get the updateBy but is not always correspond the user who made the comment.

I manage to add the getAvatar and getAuthorName but i can't manage to get the user id is it any method to do that?

Thaks again

**Comment by ihorchepurnyi** [comment]
CommentModel has attribute `createdBy`, you can use this attribute.

**Comment by eduardo-g-silva** [comment]
Yes it work perfect sorry it was my js playing tricks :(

**Comment by ihorchepurnyi** [comment]
You're welcome :)
