### ISSUE TITLE
How to show only the comments related to this activeRecord / url

### ISSUE THREAD

**Issue by eduardo-g-silva** [yii2mod/yii2-comments#55]
Hi Igor,
Sorry to bored you with a silly question but I cant manage to filter the record comments all rest it is looking beautiful.

```
<?php
echo \yii2mod\comments\widgets\Comment::widget([
    'model' => $book,
    'commentView' => '@frontend/views/comments/index', // path to your template
    //'relatedTo' => 'User ' . \Yii::$app->user->identity->username . ' commented on the page ' . \yii\helpers\Url::current(),
    'relatedTo' => \yii\helpers\Url::current(),
    'maxLevel' => 2,
    // set `pageSize` with custom sorting
    'dataProviderConfig' => [
        'sort' => [
            'attributes' => ['id'],
            'defaultOrder' => ['id' => SORT_DESC],
        ],
        'pagination' => [
            'pageSize' => 10
        ],
    ],
    // your own config for comments ListView, for example:
    'listViewConfig' => [
        'emptyText' => Yii::t('app', 'No comments found.'),
    ]
]);
?>
```
I can see that I can change the relatedTo property with any value and this change the db field but I don't understand how the model in my case $book works with the widget

thanks

**Comment by ihorchepurnyi** [comment]
Hi, `relatedTo` column only used for filtering the comments in the admin panel.

**Comment by eduardo-g-silva** [comment]
Ok, so how do I show only the comments related to an specific activeRecord or url ?

Is it a way?

**Comment by ihorchepurnyi** [comment]
Show comments for `specific model`:
```php
$model = PostModel::find()->where(['title' => 'some title'])->one();
```

Comments will be attached for this model.

**Comment by ihorchepurnyi** [comment]
```php
<?php
$model = PostModel::find()->where(['title' => 'some title'])->one();
echo \yii2mod\comments\widgets\Comment::widget([
    'model' => $model,
]);
?>
```

**Comment by ihorchepurnyi** [comment]
Also, you can create you own `dataProvider` and pass it to CommentWidget.

**Comment by ihorchepurnyi** [comment]
I prefer the first example.

**Comment by eduardo-g-silva** [comment]
It is working fine, looks like is not my day for programming.
If i provide the correct model it works as you said.  It is a complex form and i was using another variable that i use for related books instead of the activeRecord.  
Thanks  again

**Comment by ihorchepurnyi** [comment]
You're welcome.
