### ISSUE TITLE
Проблема при добавлении коментария

### ISSUE THREAD

**Issue by Lovetospuch** [yii2mod/yii2-comments#59]
Приветствую, есть такая проблема после добавления каждого 2-ого комментария если не обновлять страницу, получаю JSON такого вида {"status":"success"} вместо того чтобы остаться на той же странице. В чем может быть проблема такого поведения. Собственно actionCreate() в defaultController  
содержит данную строку return ['status' => 'success']; но почему первый комментарий добавляется без проблем а второй возвращает данный json.

**Comment by ihorchepurnyi** [comment]
Здравствуйте, скиньте пожалуйста ваш код сюда.

**Comment by Lovetospuch** [comment]
Конфиг:

`'comment' => [
            'class' => 'yii2mod\comments\Module',
        ],`

Виджет внутри view:

`<?= Comment::widget([
    'model' => $poster,
    'dataProviderConfig' => [
        'pagination' => [
            'pageSize' => 10
        ],
    ]
]) ?>`

Собственно все взял из доков.

**Comment by ihorchepurnyi** [comment]
Честно говоря не могу воспроизвести, только что добавлял комменты на сайте на котором php 7.1, mysql 5.7, yii - 2.0.11

**Comment by ihorchepurnyi** [comment]
У вас последняя версия этого модуля?

**Comment by Lovetospuch** [comment]
![image](https://cloud.githubusercontent.com/assets/8124970/24356395/717c825a-1302-11e7-8855-e0a1fb367e2c.png)
После добавления комментария так же получаю в консоли ошибку.

Да последняя.

**Comment by Lovetospuch** [comment]
Комментарий при этом добавляется.

**Comment by ihorchepurnyi** [comment]
Попробуйте такую конфигурацию

```php
<?php echo \yii2mod\comments\widgets\Comment::widget([
    'model' => $model,
    'pjaxContainerId' => 'comment-container'
]); ?>
```

**Comment by Lovetospuch** [comment]
Реакция увы та же :(

**Comment by ihorchepurnyi** [comment]
После добавления первого комментария обновляется pjax контейнер, и почему то отваливается весь js связанный с yiiActiveForm.

**Comment by ihorchepurnyi** [comment]
Честно говоря пока идей нет :(

**Comment by Lovetospuch** [comment]
Буду крутить, спасибо за помощь.

**Comment by ihorchepurnyi** [comment]
та не за что, извиняюсь что не смог помочь вам пофиксить проблему

**Comment by Lovetospuch** [comment]
Проблему решил, может кому то будет интересно.
Проблема заключалась в том что прошлый программист подключил сразу 2 jquery который идет из под коробки и сторонний отсюда конфликт. Так же тот jquery что шел из под коробки почему то не функционировал должным образом, подключил последнюю версию и все гуд.

**Comment by ihorchepurnyi** [comment]
Супер, большое спасибо за фидбек
