### ISSUE TITLE
Is there a way to getChildren works with orderBy

### ISSUE THREAD

**Issue by carlosgarcia8** [yii2mod/yii2-comments#62]
I would like to see the replies of a comment with the oldest at first and the newer at the bottom, like youtube. Is it possible? By default it works the other way around.

Example:
carlos --  Hii 2 days ago
      anonymous  -- Bye 1 day ago
      masteroftea  -- Haha 1 minute ago

**Comment by ihorchepurnyi** [comment]
Hi, by default I have the following order of comments - [link](http://awesomescreenshot.com/09e6akkg81)

All oldest replies of comments at first

**Comment by carlosgarcia8** [comment]
Thats how I would like it to be, but this is what Im getting - [link](https://gyazo.com/33f7c2f2f582c346c4731211f83e392c)

**Comment by ihorchepurnyi** [comment]
You need to create your own CommentModel and override `getTree` method with the custom sorting

**Comment by ihorchepurnyi** [comment]
What MySQL version do you use?

**Comment by carlosgarcia8** [comment]
I am using PostgreSQL 9.5.6, so I need to override the CommentModel, use the yii2mod\comments\models\CommentModel as the base and extends from it, then override the getTree to make my custom sorting, right?

**Comment by ihorchepurnyi** [comment]
yes, you right. After that, you need to override `commentModelClass` in the CommetModule by the following code:
```php
'modules' => [
    'comment' => [
        'class' => 'yii2mod\comments\Module',
        'commentModelClass' =>  'path to your custom CommentModel',
    ],
]
```

**Comment by carlosgarcia8** [comment]
Okay, Thank you for your answers. By the way, the problem that your default sort is different than mine is because I use postgresql and you mysql? That makes no sense to me

**Comment by ihorchepurnyi** [comment]
I agree with you, but I don't know why comments in our projects have different sorting.

**Comment by carlosgarcia8** [comment]
Well, I'm going to override it and work on it and if I find out why we have different sorting I'll let you know.

**Comment by ihorchepurnyi** [comment]
Ok, thanks!

**Comment by ihorchepurnyi** [comment]
I added [order](https://github.com/yii2mod/yii2-comments/blob/master/models/CommentModel.php#L242) to `getTree`. Can you update your package to `dev-master` version and check it again?

**Comment by carlosgarcia8** [comment]
Yea this way it works as it has to!

**Comment by ihorchepurnyi** [comment]
Cool, thanks!
