### ISSUE TITLE
Не корректно работае дерево в yii2 advansed

### ISSUE THREAD

**Issue by tixaskiy** [yii2mod/yii2-comments#64]
есть проблема с построением дерева комментариев. Подключаю модуль во frontend при использовании комментариев без ветвления( только первый уровень), все работае отлично. Если использовать ветвление(погружение),то как только я делаю ответ на последний опубликованный комментарий, ответ отображается, но перестает отображатся последующие комментарии предидущего уровня, то есть не ответ на комментарий, а комментарий в верхнего уровня. В базу он записыватся, но в виде он не выводится. Можете меня помочь?

**Comment by ihorchepurnyi** [comment]
Попробуйте ваш модуль обновить на версию dev-master, я делал фикс для этой проблемы, но еще не создал релиз.

**Comment by tixaskiy** [comment]
Спасибо за оперативность ответа, а как правильно мне его обновить? устанавливал через компосер

**Comment by tixaskiy** [comment]
И еще приходится комментировать эту строку в конфиге -  'enableInlineEdit' => false, если не закоментить то приложение дает сбой  
Setting unknown property: yii2mod\comments\Module::enableInlineEdit

**Comment by ihorchepurnyi** [comment]
в composer.json напишите следующее
```
"yii2mod/yii2-comments": "dev-master"
```
и после этого  сделайте в консоли `composer update`

**Comment by tixaskiy** [comment]
спасибо большое, а насчет 'enableInlineEdit' => false ?

**Comment by ihorchepurnyi** [comment]
> И еще приходится комментировать эту строку в конфиге - 'enableInlineEdit' => false, если не закоментить то приложение дает сбой
Setting unknown property: yii2mod\comments\Module::enableInlineEdit

Это потому что у вас старая версия комментариев.

**Comment by ihorchepurnyi** [comment]
> спасибо большое, а насчет 'enableInlineEdit' => false ?

Если у вас есть юзер с ролью `admin`, то он может редактировать все комментарии на фронтенде, без необходимости заходить в админку.

**Comment by ihorchepurnyi** [comment]
Выглядит это [так](http://awesomescreenshot.com/0116aqbp57)

**Comment by tixaskiy** [comment]
,С построением комментариев всё отлично, заработало, спасибо. 'enableInlineEdit' => false теперь не вызывает ошибку. Правда доступ на правку есть у всех зарегистрированных пользователей, но это скорее всего из-за того что у меня не правильно организована система ролей. Я планировал что модерация комментариев будет через backend, так что  'enableInlineEdit'  не столь важен.  Вам огромное спасибо.

**Comment by ihorchepurnyi** [comment]
И вам спасибо за issue. Рад помочь!
