### ISSUE TITLE
Problem with custom js file on creating comments

### ISSUE THREAD

**Issue by carlosgarcia8** [yii2mod/yii2-comments#65]
I have an event attached to, for example, the reply option, but when a comment is created, everything is reloaded and the event is lost. I see that your comment.js is reloaded every time it creates a comment, how would I add my custom js file to that?

**Comment by ihorchepurnyi** [comment]
You can create your own comment.js file and update CommentAsset by the following code:

```php
// in your application configuration

'assetManager' => [
    'bundles' => [
        'yii2mod\comments\CommentAsset' => [
            'js' => [
                'path to your own comments.js file',
            ]
        ],
    ],
]
```

**Comment by carlosgarcia8** [comment]
I'm currently trying to add some code to the comment.js and I am a bit lost. I am trying to add an event after all the comments are created so that I can add them, basically I am working with upvotes and downvotes with the comments, but when I add a new comment the event on click of every upvote/downvote is lost. With the comment.js I am having trouble trying to figure it out how to make it happen. Any help please?

**Comment by ihorchepurnyi** [comment]
I create issue for this feature - https://github.com/yii2mod/yii2-comments/issues/66
I'll try to solve this issue today.
