### ISSUE TITLE
comment/manage Forbidden (#403)

### ISSUE THREAD

**Issue by koquipizzi** [yii2mod/yii2-comments#68]
I am using mdmsoft in order to adminitrate the accesses rules and I can not access to the comment admin.

I have 
```
'admin' => [
           'class' => 'mdm\admin\Module',
           'layout' => 'left-menu', // defaults to null, using the application's layout without the menu
        ],
```
and 
```
'authManager' => [
             'class' => 'yii\rbac\DbManager', 
        ],

```

What I should do for fix it?
Thanks!

**Comment by ihorchepurnyi** [comment]
If you are logged in as user with `admin` role, then you don't need to assign route. Also, you can override [access control configuration](https://github.com/yii2mod/yii2-comments/blob/master/controllers/ManageController.php#L39)

**Comment by ihorchepurnyi** [comment]
Which role assigned to your user?

**Comment by koquipizzi** [comment]
Hi Igor, Great!
I am using another role, so.. I changed the access control configuration.
Have a nice day!

**Comment by ihorchepurnyi** [comment]
Cool, have a nice day!
