### ISSUE TITLE
Document that module name must be comment

### ISSUE THREAD

**Issue by mtangoo** [yii2mod/yii2-comments#69]
I had been fighting an error that I could not understand until I looked into sources. In module trait the module is hardcoded as "comment" and I had it as comments. I would prefer a Widget setting where we can pass module name or if it have to remain hardcoded then it should clearly be stated to avoid pains like mine.

Thank you for great extensions. I personally appreciate them

**Comment by ihorchepurnyi** [comment]
Hi, you can change documentation and create PR for this issue.

**Comment by mtangoo** [comment]
>Hi, you can change documentation and create PR for this issue.

https://github.com/yii2mod/yii2-comments/pull/70

**Comment by ihorchepurnyi** [comment]
Thanks
