### ISSUE TITLE
Question about the extra security code

### ISSUE THREAD

**Issue by andrewpros** [yii2mod/yii2-comments#74]
Hi.
Can someone explain to me whats the whole point of the encryption stuff? Well i get the intentions, probably, but it will not stop any bot software right?

**Comment by ihorchepurnyi** [comment]
Encryption used to prevent changing the attributes of the model, for example `parentId`

**Comment by ihorchepurnyi** [comment]
In 2.0 version encryption will be deleted.

**Comment by andrewpros** [comment]
Oh i see, is there a ETA on 2.0?

**Comment by ihorchepurnyi** [comment]
Now I don't have time to develop extensions, I will try to release version 2.0 in September.

**Comment by andrewpros** [comment]
ok, thx
