### ISSUE TITLE
Problem with level tree after editing or deleting comment

### ISSUE THREAD

**Issue by ztdan4ik** [yii2mod/yii2-comments#75]
Hi all!
Thanks for your work with Yii2 Comments Extension. It really great!

Now I found one problem with level in comments tree.
I'm using default model and views.
Problem is, when I edited or delete comment with level > 1, after the action level of edited or deleted comment is upping. And it can be more then maxLevel, so with this case comment not showing.
I think, with that actions level should not up. Am i right? 
You can see my short screen video, where I displaying a problem http://i.de-v.net/1504869692.webm

My module configuration is:

```
        'comment' => [
            'class' => 'yii2mod\comments\Module',
            'enableInlineEdit' => true,
            'controllerMap' => [
                'default' => [
                    'class' => 'yii2mod\comments\controllers\DefaultController'
                ]
            ]
        ],
```

Thanks for you answer!

**Comment by ihorchepurnyi** [comment]
Hi, I'll check your problem. Thanks for issue

**Comment by ihorchepurnyi** [comment]
I fixed it, please update this package to `dev-master` version and check it.
