### ISSUE TITLE
Does it work within ActiveForm ??

### ISSUE THREAD

**Issue by aagge** [yii2mod/yii2-comments#79]
Hi,

Does your widget work when enclosed in ActiveForm? It shows but does not save. Is this expected behavior? Can I make it work within ActiveForm?

<?php $form = ActiveForm::begin(); ?>

    <?php echo \yii2mod\comments\widgets\Comment::widget([
	         'model' => $model,
                 'dataProviderConfig' => [
                 'pagination' => [
                 'pageSize' => 5
                ],
         ]]); ?>  

<?php ActiveForm::end(); ?>

**Comment by ihorchepurnyi** [comment]
Hi, you can't, Comment widget already included [ActiveForm](https://github.com/yii2mod/yii2-comments/blob/master/widgets/views/_form.php)
