### ISSUE TITLE
jquery.pjax.js:233 Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by bahrammzm** [yii2mod/yii2-comments#80]
I have used kartik/treemanager extension model for this extension . Everything work as well for initial node , but when i change the node of tree and after that submit the comment , comment button stuck in "loading..." and shows the below error . although comment saved in database .

![capture](https://user-images.githubusercontent.com/15061349/31671888-df8f13ba-b367-11e7-86cc-cd366dd047b7.PNG)

**Comment by ihorchepurnyi** [comment]
I don't have time to fix this issue now and I never used this extension with `kartik/treemanager`.  Can you fix this issue and submit PR for this issue?

**Comment by bahrammzm** [comment]
How can disable pjax for form submit at all?

**Comment by ihorchepurnyi** [comment]
You need to create own view and override this [property](https://github.com/yii2mod/yii2-comments/blob/master/widgets/Comment.php#L37) for Comment widget

**Comment by bahrammzm** [comment]
i think this issue is because every node content load via ajax in `kartik/treemanager` and somethings lose for reload comments via pjax . But still can't fix it...

**Comment by bahrammzm** [comment]
i found the solution .
1-  set a Flash message in actionCreate in DefaultController that store `$commentModel->entityId` value  
`Yii::$app->session->setFlash('commentSaved',  $commentModel->entityId);`
2-  set displayValue property  in `kartik/treemanager` with that Flash message  
`'displayValue' => (Yii::$app->session->hasFlash('commentSaved') ? Yii::$app->session->getFlash('commentSaved') : Tree::find()->min('id')),`
3- replace `$.pjax(pjaxSettings);` to `location.reload();` in comment.js , function createComment

**Comment by ihorchepurnyi** [comment]
Nice!
