### ISSUE TITLE
Can I use it for not an authorized users?

### ISSUE THREAD

**Issue by Legion112** [yii2mod/yii2-comments#81]
I'm using advanced environment.
And me need to use it for not authorized users. 
Can I do it?

**Comment by ihorchepurnyi** [comment]
Hi, no, you can't add comments as an unauthorized user.

**Comment by ihorchepurnyi** [comment]
I'm sorry, I don't have enough time to implement this feature.

**Comment by Legion112** [comment]
That's too bad. 
But thank you for answer, you saved my time.
