### ISSUE TITLE
Не работает создание комментариев

### ISSUE THREAD

**Issue by AlexMetalcore** [yii2mod/yii2-comments#86]
Здравствуйте, подлючил ваш виджет https://prnt.sc/kk3t6i,  при попытке отправки выдает ошибку 
![2018-08-18 14-55-35](https://user-images.githubusercontent.com/15331725/44299031-dc829500-a2f6-11e8-8eeb-38eb09c86856.png) + логи 
![2018-08-18 14-57-16](https://user-images.githubusercontent.com/15331725/44299044-089e1600-a2f7-11e8-862f-a4576b3a447e.png)

**Comment by ihorchepurnyi** [comment]
Здравствуйте, покажите пожалуйста ошибку целиком

**Comment by AlexMetalcore** [comment]
Добрый вечер! вот -  https://prnt.sc/kn4fd8

**Comment by ihorchepurnyi** [comment]
Спасибо, и можете пожалуйста скинуть версию Yii

**Comment by AlexMetalcore** [comment]
пожалуйста, https://prnt.sc/knae7e

**Comment by ihorchepurnyi** [comment]
Супер, сегодня гляну и отпишу вам.

**Comment by AlexMetalcore** [comment]
Отлично, спасибо

**Comment by ihorchepurnyi** [comment]
Проверил только что создание комментариев в шаблоне - https://github.com/yii2mod/base
Вот [скриншот](http://joxi.ru/xAeg3Kjtp54Bjm)
[Конфигурация](http://joxi.ru/BA05wEZTJZx7Er)

Проверьте пожалуйста настройку у вас модуля. Можете посмотреть как он настроен в пакете [cms](https://github.com/yii2mod/yii2-cms)

**Comment by ihorchepurnyi** [comment]
Для тестирования можете поднять https://github.com/yii2mod/base через докер, там уже установлен модуль.

**Comment by AlexMetalcore** [comment]
у меня шаблон https://github.com/yiisoft/yii2-app-advanced , ставил по мануалу https://github.com/yii2mod/yii2-comments , ругаеться на то что данного контроллера и екшена нету 'action' => Url::to(['comment/default/create', 'entity' => $encryptedEntity]),
 (/var/www/html/yii/vendor/yii2mod/yii2-comments/widgets/views/_form.php) ну ведь это модуль, поставил и никуда лезть не надо) . В файле main.php (конфигурации приложения) подключил модуль 'modules' => [
        'comment' => [
            'class' => 'yii2mod\comments\Module',
        ],
    ], 
так же транслит 'i18n' => [
            'translations' => [
                'yii2mod.comments' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@yii2mod/comments/messages',
                ],
            ],
        ],
я верю что в шаблоне бейс он работает, но хотелось что бы и у меня заработало

**Comment by AlexMetalcore** [comment]
Спасибо вам, хочеться решить вопрос все же на едвенсед Yii

**Comment by AlexMetalcore** [comment]
вот сам виджет в виде  <?= \yii2mod\comments\widgets\Comment::widget([
            'model' => $model,
            'maxLevel' => 2,
            'dataProviderConfig' => [
                'pagination' => [
                    'pageSize' => 10
                ],
            ],
            'listViewConfig' => [
                'emptyText' => Yii::t('app', 'Комментариев нету'),
            ],
        ]); ?>

**Comment by AlexMetalcore** [comment]
слушайте, подправил свои правила rules все заработало, супер

**Comment by ihorchepurnyi** [comment]
Отлично, спасибо!

**Comment by lightsid** [comment]
> слушайте, подправил свои правила rules все заработало, супер

Подскажите пожалуйста, в чем именно была проблема с rules ?
