### ISSUE TITLE
"Carbon 1 is deprecated" warning

### ISSUE THREAD

**Issue by kwazaro** [yii2mod/yii2-comments#92]
Hello! Recently I become to get this warning during composer update. Seems that yii2mod/yii2-behaviors depends on deprecated package "nesbot/carbon ~1.0".

**Comment by ihorchepurnyi** [comment]
Thanks for the issue, I'll update `yii2mod/yii2-behaviors `

**Comment by ihorchepurnyi** [comment]
created new release - https://github.com/yii2mod/yii2-behaviors/releases/tag/2.0

**Comment by kwazaro** [comment]
Still can't update. Did you merged release branch?
